---
functional:
  - Пользователь должен иметь возможность просматривать подробную информацию о товаре (название, рейтинг, цена со скидкой и без нее) 
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары каталога постраничным выводом
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность удалять товары из корзины на странице корзины
  - Пользователь должен иметь возможность со страницы корзины перейти обратно в каталог
  - Пользователь должен иметь возможность оформить заказ на странице корзины с переходом на страницу оплаты
  - Корзина должна храниться в сессионых куках
non-functional:
  - Сайт должен быть разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт должен обрабатывать большое количество трафика
implicit:
  - Пользователь должен интуитивно понимать, где меняется локализация сайта, даже на неизвестном ему языке (С помощью флагов)
  - Пользователь должен иметь возможость зарегистрировать личный аккаунт
  - Пользователь должен иметь возможость просмотреть сделанные заказы
  - Пользователь должен иметь возможность быстро полностью очистить корзину
  - Пользователь должен иметь возможость добавить товар в избранное
  - Пользователь должен иметь возможость посмотреть просмотренные ранее товары
  - Пользователь должен иметь возможость изменять количество добавленного товара на странице корзины
  - Пользователь должен видеть сколько товаров у него в корзине, находясь вне корзины
  - Пользователь должен видеть стоимость всех товаров в корзине 
  - Пользователь должен видеть сумму стоимости товара для каждой позиции в корзине
  - У пагинации должна указываться текущая страница
